services:
  koshelek-receiver:
    container_name: koshelek-receiver
    image: evpatiykaloed/koshelek.receiver:1.0.0
    ports:
      - "7091:8080"
      - "7092:8081"

    restart: unless-stopped
    volumes:
     - ./src/Receiver/Web/appsettings.json:/app/appsettings.json
    environment:
     - ASPNETCORE_URLS=http://+:8081;http://+:8080
     - DOTNET_RUNNING_IN_CONTAINER=true
     

  koshelek-streamer:
    image: evpatiykaloed/koshelek.streamer:1.0.0
    ports:
      - "7103:8080"
      - "7104:8081"

    restart: unless-stopped
    volumes:
     - ./src/Streamer/Web/appsettings.json:/app/appsettings.json
    environment:
     - ASPNETCORE_URLS=http://+:8080
     - DOTNET_RUNNING_IN_CONTAINER=true
    

  koshelek-frontend:
    container_name: koshelek-frontend
    image: evpatiykaloed/koshelek.frontend:1.0.0
    ports:
      - "7105:80"
   

  koshelek-history:
    container_name: koshelek-history
    image: evpatiykaloed/koshelek.datahistory:1.0.0
    ports:
      - "7094:8080"
      - "7095:8081"
    restart: unless-stopped
    volumes:
     - ./src/DataHistory/Web/appsettings.json:/app/appsettings.json
    environment:
     - ASPNETCORE_URLS=http://+:8080
     - DOTNET_RUNNING_IN_CONTAINER=true
